"""agregar slug modelo products

Revision ID: 01f8efd5245e
Revises: aaf5e2966642
Create Date: 2021-03-11 17:33:30.272539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f8efd5245e'
down_revision = 'aaf5e2966642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('slug', sa.String(length=120), nullable=True))
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'slug')
    # ### end Alembic commands ###
