"""agregar el atributo imagen

Revision ID: 0ab1b19f3980
Revises: 01f8efd5245e
Create Date: 2021-03-12 15:42:54.021308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab1b19f3980'
down_revision = '01f8efd5245e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('prodcuto_img', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'prodcuto_img')
    # ### end Alembic commands ###
